spring:
  datasource:
    username: root
    password: Ali_005448
    url: jdbc:mysql://39.106.169.107:3306/study?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver